### ISSUE TITLE
SWF Version

### ISSUE THREAD

**Issue by delahee** [markknol/hxobfuscator#1]
Hey!

This is a very cool project, do you have a swf version working? Tried it on my codebase but failed with a List.map2 ocaml exception

Thanks!

**Comment by markknol** [comment]
No didn't try it for swf, only js yet.
Have to admit the current status is: if you are lucky, it could work. There are several complex issues when it comes to overriding but also interfaces.

**Comment by delahee** [comment]
Okay no problem :)
